global:
  scrape_interval: 15s 
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  # - job_name: 'vault'
  #   static_configs:
  #     - targets: ['statsd:9102']
  - job_name: 'vault'
    metrics_path: /v1/sys/metrics
    params:
      format: ['prometheus']
    bearer_token: prometheus-token
    static_configs:
      - targets: ['vault-1:8200','vault-2:8200','vault-3:8200']